### ISSUE TITLE
Where to find information on deprecation warnings?

### ISSUE THREAD

**Issue by bennyn** [jasmine/jasmine.github.io#102]
I have read the [Jasmine setup for Node.js](https://jasmine.github.io/setup/nodejs.html) and copied over the `jasmine.json` configuration which is shown there:

```json
{
  "spec_dir": "spec",
  "spec_files": [
    "**/*[sS]pec.js",
    "!**/*nospec.js"
  ],
  "helpers": [
    "helpers/**/*.js"
  ],
  "stopSpecOnExpectationFailure": false,
  "random": false
}
```

When running Jasmine 3.3 with this configuration, I am getting the following warnings:

> DEPRECATION: Setting throwOnExpectationFailure directly on Env is deprecated, please use the oneFailurePerSpec option in `configure`
> DEPRECATION: Setting randomizeTests directly is deprecated, please use the random option in `configure`

When removing `stopSpecOnExpectationFailure` and `random` from my `jasmine.json`, everything is fine. 

Can you tell me where to find the `configure` option, so that I can use `throwOnExpectationFailure` and `randomizeTests`?

**Comment by slackersoft** [comment]
Jasmine 3.3.1 (node.js/npm only) should resolve these deprecation warnings. It looks like I didn't get the node.js wrapper updated for the new API (see jasmine/jasmine-npm#145). I believe this new version is the nicer fix for this error.

**Comment by Laoujin** [comment]
In `spec/helps/helpers.js`
```js
jasmine.getEnv().configure({
  failFast: false,
  hideDisabled: false,
  oneFailurePerSpec: false,
  random: true,
  seed: null, // null=random. Or use func: () => 4547;
  // specFilter: spec => spec.description.includes('NEEDLE'),
});
```

Docs: https://jasmine.github.io/api/edge/Configuration.html

**Comment by slackersoft** [comment]
Closing this as I believe it has been resolved.
