### ISSUE TITLE
Inappropriate Title of the Docs Page

### ISSUE THREAD

**Issue by vinitshahdeo** [jasmine/jasmine.github.io#112]
The title of [this](https://jasmine.github.io/2.0/introduction.html) page is `introduction.js`, which doesn't seem to be appropriate.

It should be something similar to **Introduction to Jasmine**

**Comment by slackersoft** [comment]
I agree that that particular title isn't super obvious. Unfortunately, we've pretty heavily revamped the way that the docs are setup so it's difficult to generate new docs for versions that old. Given how old Jasmine 2.0 is as well, I'm not sure how valuable updating this would be to the community. I would encourage you to upgrade to a more recent and supported version of Jasmine.

**Comment by sephie** [comment]
For what it's worth, I just realized that the nice-looking "introduction.js" is for an old version. A notification/link to the current 3.4 docs would be useful.

**Comment by pragapraga** [comment]
@vinitshahdeo Is this corrected , If yes please close the Issue :)

**Comment by slackersoft** [comment]
Closing this, now that we have a warning and link to newer versions of the documentation.
