### ISSUE TITLE
Differentiating from jest?

### ISSUE THREAD

**Issue by elliot-nelson** [jasmine/jasmine.github.io#118]
Jest has become very popular for the current JavaScript ecosystem (npm packages, react app unit testing, etc.).  Since jest is seen widely as "jasmine, but faster and with some new stuff", it's not obvious why someone would pick jasmine for a new project over jest.

It doesn't look like jasmine is being sunset in favor of jest, so maybe it makes sense to have a section somewhere explaining why you _would_ pick jasmine?  An environment it excels in, maybe a different mock/stub approach, total lib size...

I guess this is both a potential doc update and just picking the brain of the jasmine maintainers...

**Comment by slackersoft** [comment]
This is the kind of thing that is usually hard to write without coming off as defensive. Realistically, there's not going to be a way for me to compete with Facebook and the fact that Jest is the default when you use create-react-app. In a pinch, I would probably mostly lean towards Jasmine not being too closely bound up with any given web framework.

**Comment by matthewjh** [comment]
Jasmine is also very lightweight - doesn't come with a bunch of stuff you may or may not need.

**Comment by nbilyk** [comment]
The main reason I chose Jasmine is because of the browser runner. I didn't find a clear path to running Jest in a browser. There are a couple edge cases Jest does better, but for the most part they're pretty similar.

**Comment by sgravrock** [comment]
I think the main points we've got on the home page today (fast/low overhead, no magic, node and browser) do a decent job of differentiating without too much risk of coming off as defensive or becoming obsolete if something else eclipses Jest in popularity.
