### ISSUE TITLE
Duplication of examples

### ISSUE THREAD

**Issue by didaquis** [jasmine/jasmine.github.io#128]
There are a lot of examples duplicated on docs. Example of "toBeDefined()" is one of them

![image001](https://user-images.githubusercontent.com/6883041/73313610-00584300-422c-11ea-94ab-055436e4456e.png)

**Comment by slackersoft** [comment]
Thanks for logging this. I'm not entirely sure what happened, but I've regenerated the API docs and it looks correct now.
