### ISSUE TITLE
Testing uncaughtExceptions and unhandledRejections

### ISSUE THREAD

**Issue by jcald1** [jasmine/jasmine.github.io#130]
I'm using Jasmine 3.5.0.  I have an uncaught rejection and uncaught exception handlers.

```
const handleUncaughtExceptions = ({ logger }) => {
  process.on('uncaughtException', err => {
    const err2 = error(
      errors.system.UNCAUGHT({
        debug : { originalError : err }
      })
    );
    logger ?  logger.err(err2) : consoleLogIfLoggerNotSetUp(err2);
    throw err2;
  });

  process.on('unhandledRejection', (reason, promise) => {
    const promiseError =
            reason instanceof Error ? reason : new Error('unhandledRejection');
    const err = error(
      errors.system.UNCAUGHT({
        message : 'unhandledRejection',
        debug   : { reason, originalError : promiseError, promise }
      })
    );
    logger ?  logger.err(err) : consoleLogIfLoggerNotSetUp(err);

    if (!process.env.ALLOW_DEBUG || process.env.ALLOW_DEBUG === 'true') {
      throw err;
    }
  });
};
```

Test:

```
describe('error', () => {
  fit('handles uncaught errors', done => {
    handleUncaughtExceptions({ logger });
    var uncaughExceptionHandlers = process.listeners('uncaughtException');
    let exceptionListener = uncaughExceptionHandlers.pop();
    while (exceptionListener) {
      process.removeListener('uncaughtException', exceptionListener);
      exceptionListener = uncaughExceptionHandlers.pop();
    }
    // No exception handlers here when printing process.listeners('uncaughtException')
    process.on('uncaughtException', (err)=> () => done());
    Promise.reject(new Error('Rejected Error'));
  });
});
```

So the unhandled rejection does throw an exception at the end as expected, and since I removed any uncaughtException handlers in the test (including Jasmine's), only my test uncaughtException handler should be called.  I call done() in my uncaughtException handler and expect the test to complete successfully, but instead I get:

```
Failures:
1) error handles uncaught errors
  Message:
    Unhandled promise rejection: Error: Rejected Error
  Stack:

```

When I replace done with a console statement, it does write to the console.

The error object has a reference to the unhandled Promise.  I also tried catching it in the test but I'm still getting the same result.  It's like Jasmine is caching the unhandled exception somehow.

Is there a way to test uncaughtException and unhandledRejection handlers in Jasmine?  I saw this post: https://www.exratione.com/2015/10/node-js-how-to-unit-test-an-uncaught-exception-handler/, but `global.suppressUncaughtExceptionHandling` didn't seem to do anything.

**Comment by sgravrock** [comment]
Jasmine 4.3 adds [spyOnGlobalErrorsAsync](https://jasmine.github.io/api/4.3/jasmine.html#.spyOnGlobalErrorsAsync) which might solve your problem. Prior to 4.3, I'm not aware of a way to prevent unhandled rejections from being treated as failures in Node. There's a [browser-specific workaround](https://github.com/jasmine/jasmine/pull/1860) in 3.7 and later, but that doesn't apply here.
