### ISSUE TITLE
Getting 404 on every page

### ISSUE THREAD

**Issue by marvinhagemeister** [jasmine/jasmine.github.io#132]
Every documentation page I've tried to access returns a 404. Maybe this has something to do with the recent switch from `master` to `main` as the default branch? Could be that the GitHub pages settings haven't been updated to reflect that. On my own repo's I don't even have that option to chose a branch other than `master` or `gh-pages`:

![Screenshot from 2020-06-27 09-40-25](https://user-images.githubusercontent.com/1062408/85917438-53c1d200-b85a-11ea-9a2b-8321c2bb2d41.png)

Steps to reproduce:

1. Go to https://jasmine.github.io/

Possible solution:

Rename `main` branch to `gh-pages` and change the repo settings accordingly.

**Comment by sgravrock** [comment]
Fixed. Thanks for letting us know.
