### ISSUE TITLE
Your first suite tutorial - Section on Spies has a link that gives 404

### ISSUE THREAD

**Issue by DamianArado** [jasmine/jasmine.github.io#148]
The [tutorial page on Your first suite](https://jasmine.github.io/tutorials/your_first_suite) has a section on Spies that says:

You can define what the spy will do when invoked with [and](https://jasmine.github.io/api/edge/Spy_and.html).

But this link is giving a 404. What needs to be fixed here? Thanks.

**Comment by sgravrock** [comment]
Fixed. Thanks for the report.
