### ISSUE TITLE
how to match pointers/references?

### ISSUE THREAD

**Issue by allan-bonadio** [jasmine/jasmine.github.io#149]
I have code that has linked lists.  I have to test to see if that pointer points to this object.  Just a simple === comparison.  Instead, I've been using toEqual(), which is tedious, especially since there's some circular loops in my pointers.  I would think there's a matcher for this simple situation, but I wasn't able to find any.  What am I missing?  Do I have to make a custom matcher?

**Comment by sgravrock** [comment]
The [`toBe` matcher](https://jasmine.github.io/api/4.1/matchers.html#toBe) does a === comparison.
