### ISSUE TITLE
Jump to method in docs

### ISSUE THREAD

**Issue by KyleW** [jasmine/jasmine.github.io#151]
The new doc format is great, but since it's no longer a single long page, I can't use my browsers "find" to jump to the line I want.

It would be great to add some version of search to the docs. Or maybe just add a second level to the outline on the left side of the page.

**Comment by sgravrock** [comment]
Closing since the search functionality meets this need pretty well in my experience, and we haven't heard anything new since 2018. Anyone who disagrees should feel free to open a new issue with specifics.
