### ISSUE TITLE
Response method is invalid in ajax.js

### ISSUE THREAD

**Issue by jfairbank** [jasmine/jasmine.github.io#20]
Hello, I think the docs for ajax.js need to be updated to use `respondWith` (https://github.com/jasmine/jasmine-ajax/blob/master/src/fakeRequest.js#L240) instead of `response` for stubbed requests. Here is [one](https://github.com/jasmine/jasmine.github.io/blob/master/2.2/src/ajax.js#L51-L64) for example. I don't know what, if any, are the dependencies among jasmine core and jasmine ajax, but I'd be happy to PR the changes to whichever core versions need it.

**Comment by slackersoft** [comment]
Jasmine-ajax 3.0 was released a little before jasmine 2.2, so it probably makes sense to change it in both 2.2 and edge. I'd be happy to review a pull request that updates the examples and puts the new version of the library in.
