### ISSUE TITLE
Update docs for node.js usage

### ISSUE THREAD

**Issue by slackersoft** [jasmine/jasmine.github.io#23]
The [node.js docs](https://jasmine.github.io/edge/node.html) are currently very basic and don't do a very good job of covering some of the details of how the jasmine npm works.

Things that would be good to see:
1. ~~An example `jasmine.json`~~ ([done](https://jasmine.github.io/edge/node.html#section-Configuration))
2. ~~How to install the examples~~ ([done](https://jasmine.github.io/edge/node.html#section-Generate_examples))
3. ~~How to use jasmine as a library instead of just as a command line utility~~ ([done](https://jasmine.github.io/edge/node.html#section-Using_the_library))
4. How to set up a helper to allow loading coffee script and other non-es5 scripts

There may be other things as well. Feel free to send pull requests for subsets of this list, it doesn't need to be done in one shot.

**Comment by MartinMuzatko** [comment]
Please create a complete doc. There are a few `require` missing in the node.js docs.
Unknown `this`
Unknown `util`

**Comment by amypellegrini** [comment]
Sorry, is there any reason for which "An example jasmine.json" was dashed from the list of nice-to-haves? I just want to find out if there is any setting to exclude folders or files when running jasmine from the console. Should I use a regex? Is there a setting for this? How does it work?

I mean, there are examples and all, but this particular use case (excluding folders and files from config) is not covered, and it would definitively be a nice-to-have feature.

Thanks!

**Comment by slackersoft** [comment]
@MartinMuzatko the current node.js docs aren't necessarily meant to be able to be loaded into a single file and executed, but to serve as an example of what that kind of custom functionality might look like. Some of the parts in there are an example json file and commands to run.

@amypellegrini  That item is crossed off because [there is one](https://jasmine.github.io/edge/node.html#section-Configuration) in the current docs. Currently there is no way to explicitly exclude files, only pick which files to include.

Hope this helps. Thanks for using Jasmine.

**Comment by slackersoft** [comment]
The new [react tutorial](https://jasmine.github.io/tutorials/react_with_npm) should complete the final bullet point. Closing.
