### ISSUE TITLE
Missing documentation for `done.fail`?

### ISSUE THREAD

**Issue by emmenko** [jasmine/jasmine.github.io#26]
When running async specs, you may want to let the spec fail by using `done.fail`.
However, I haven't found any mention in the documentation related to this. Any reason why or you have just forgot to put it there?

Thanks

**Comment by slackersoft** [comment]
Unfortunately, with the way we currently have our documentation set up, it is a bit difficult to document the features that would cause a spec to fail. The specs that you see on the right are actually run at the bottom of the page, so if anything were to actually use `fail` or `done.fail` we would have a red spec and our documentation build would be in a failing state.

I'd be happy to review a pull request that documented these features without breaking the suite.

**Comment by emmenko** [comment]
The spec doesn't need to fail, but you have it in the code as a way to make the spec fail if your async function returns an error.

Example:

```js
it('should fetch google.com', done => {
  fetch('http://google.com')
    .then(res => {
      expect(res.status).toBe(200)
      done()
    })
    .catch(done.fail) // make the spec fail in case of error
})
```

**Comment by slackersoft** [comment]
#37 has been merged, closing.
