### ISSUE TITLE
Add link to download the release zip on home page

### ISSUE THREAD

**Issue by shirishp** [jasmine/jasmine.github.io#45]
On landing page, there is no way to know how to download the release version of Jasmine.js.

It would be great if we can provide link to [Release page](https://github.com/jasmine/jasmine/releases)

**Comment by JoseRoman** [comment]
There is a download section at the bottom of the page.  
![image](https://cloud.githubusercontent.com/assets/4240075/10119674/383cf2f6-6451-11e5-9793-c112524a1514.png)

**Comment by shirishp** [comment]
That's my point. I think it would be much easier to download and then follow the introduction, than reading all the introduction and then find a small link to download the package.

**Comment by JoseRoman** [comment]
@shirishp I agree. @slackersoft Would you open to a PR to include download links in landing page?

**Comment by slackersoft** [comment]
Sounds reasonable for right now. We have a bit of a rework for the site in progress, but I have no idea when I'll have time to actually put it together

**Comment by slackersoft** [comment]
The new site has been turned on, including a link on the main page to the releases page on github. I think this should solve this issue. Closing

Thanks for using Jasmine!

**Comment by shirishp** [comment]
Thank you. :)

Currently site is broken because of mixed content issue. But I will verify it later.
