### ISSUE TITLE
onComplete callback deprecated

### ISSUE THREAD

**Issue by adambuczynski** [jasmine/jasmine.github.io#50]
The documentation example specifies an onComplete callback, however, when you do that and run the tests, jasmine complains that it's been deprecated. Docs should probably be updated to reflect new API?

Ref https://github.com/jasmine/jasmine/issues/979

**Comment by amavisca** [comment]
Are you referring to the [node runner](github.com/jasmine/jasmine-npm) or [core](github.com/jasmine/jasmine)? The node runner is in npm as `jasmine` while the core is `jasmine-core`. 

I'm not sure of any deprecated onComplete in the core, but I may be mistaken.

The onComplete deprecation/change in the node runner was that originally you could specify an onComplete for the constructor of the ConsoleReporter, but now we have you specify one on the jasmine instance and fire it off separately from the ConsoleReporter. I think the docs are up to date for this.

Thanks!

**Comment by adambuczynski** [comment]
Hi @amavisca, I was referring to the `onComplete` as described in the Node documentation here:

http://jasmine.github.io/edge/node.html#section-Custom_onComplete

I used that in my app, and got a deprecated warning. Would show you a screenshot of the message, but I've since moved to Mocha/Chai so I don't have the code handy anymore.
