### ISSUE TITLE
Describe what is “spec_dir” relative to.

### ISSUE THREAD

**Issue by 9662** [jasmine/jasmine.github.io#56]
`jasmine init` produces a template `jasmine.json` with the following contents:

``` json
{
  "spec_dir": "../../spec",
  "spec_files": [
    "**/*[sS]pec.js"
  ],
  "helpers": [
    "helpers/**/*.js"
  ],
  "stopSpecOnExpectationFailure": false,
  "random": false
}
```

It is not immediately clear however what `spec_dir` is relative to. The `jasmine.json` file? The location from where `jasmine` is run?

**Comment by 9662** [comment]
(likewise with `"helpers"` btw :smiley:  )

**Comment by slackersoft** [comment]
We looked into introducing comments directly in the `.json` file, but that made it no longer valid JSON when we tried to load it. We would be happy to review a pull request that updates the docs here with this info (it looks like it is relative to the project base dir)
