### ISSUE TITLE
Ember.js + Jasmine: No one?

### ISSUE THREAD

**Issue by tralston** [jasmine/jasmine.github.io#60]
I'm flabbergasted that Ember.js + Jasmine (two very popular products) haven't caught on yet. Very few blogs exist to tell the tale of their limited attempts to make one work with the other.

Does anyone have any experience getting Jasmine to play nice with Ember.js? It's not even found on the _Works with pretty much everything_ list.

Coming from rspec, I have so much hope for Jasmine, but have no idea where to start. I'm using Ember CLI v2.7.0. Even if it were just some setup/config code to start out, I could find the rest in the main docs.

**Comment by slackersoft** [comment]
Personally, I've only ever worked with Ember once, and the feeling I got at the time was that Ember didn't really want to be unit tested and really needed the entire environment booted up to check on anything.

Additionally, we generally try to keep Jasmine independent from any given framework or library, so I don't think that Jasmine's official documentation is the right place for how to hook Ember up to work with Jasmine.

Closing. Thanks for using Jasmine!

**Comment by tralston** [comment]
I'm not sure about older versions of Ember, but as of today (v2.8.0, ember-cli) you can run `ember test` and it just runs tests. I see what you mean about Ember not wanting to be tested, there's not a lot out there, and testing culture can take a while to grow in a framework.

I agree that Jasmine should be framework agnostic, but I guess I was hoping that someone (not necessarily you) out there had enough experience with it to give some starter docs on setting it up. Who knows, maybe someday I'll figure it out. Thanks!
