### ISSUE TITLE
https://jasmine.github.io/ can't load css

### ISSUE THREAD

**Issue by sateffen** [jasmine/jasmine.github.io#63]
Hey,

all browsers (firefox, IE and chrome) refuse to load the CSS from [https://jasmine.github.io/](https://jasmine.github.io/) because the protocol, which is used. The CSS is loaded via http, where as the page is loaded with HTTPS, so the css is considered "mixed-content", and "unsecure". This results in a page without any css.

Logs from developer console:

`
Mixed Content: The page at 'https://jasmine.github.io/pages/getting_started.html' was loaded over HTTPS, but requested an insecure stylesheet 'http://jasmine.github.io/css/jasmine_docco.css'. This request has been blocked; the content must be served over HTTPS.
getting_started.html:5
Mixed Content: The page at 'https://jasmine.github.io/pages/getting_started.html' was loaded over HTTPS, but requested an insecure stylesheet 'http://jasmine.github.io/css/site.css'. This request has been blocked; the content must be served over HTTPS.
`

**Comment by sateffen** [comment]
Connected to [this](https://github.com/jasmine/jasmine.github.io/commit/7f08ec6deec57b04bded4753f162e16c7562c926) pullrequest, so I guess the docs just need a rebuild.

Loading the page with empty cache doesn't help.

**Comment by iainbeeston** [comment]
Still not working for me. Does someone need to update the github pages settings to force ssl?

**Comment by jongunter** [comment]
Not working for me, still. Looks to be an SSL issue.

**Comment by iainbeeston** [comment]
It might be specific to firefox on desktop. Here's what I see, including the console errors showing the issue.

<img width="1061" alt="screen shot 2016-11-02 at 09 51 52" src="https://cloud.githubusercontent.com/assets/111963/19924019/0c12b48a-a0e2-11e6-9ce9-7d46c2fc3591.png">

**Comment by iainbeeston** [comment]
I can also reproduce in chrome:

![screen shot 2016-11-02 at 09 53 15](https://cloud.githubusercontent.com/assets/111963/19924054/335d28a4-a0e2-11e6-8506-a3a57e103800.png)

To reproduce the error, load the site over HTTPS

**Comment by jongunter** [comment]
Looks like stylesheets should be linked without a protocol: `<link href="//jasmine.github.io/style.css">`

**Comment by slackersoft** [comment]
The layout pages are using the `site.github.url` jekyll option to generate the css and javascript includes, to make it easier to preview pull requests and things. I just updated the settings for the repo to force SSL, but it doesn't look like that's causing github to rebuild the pages and generate the correct links.

**Comment by slackersoft** [comment]
Rebuild went through, https should work properly now
