### ISSUE TITLE
How to load Virtual Module getting created dynamically from code

### ISSUE THREAD

**Issue by rahulsahay19** [jasmine/jasmine.github.io#66]
Hi,

I am trying to write a test case for a controller where in module is not physically present. Infrastructure code is written in such a way, that module gets created dynamically when application loads. when, I am checking the logs, I can see that module is getting created programmatically, but, when I try to write expect for the controller which is dependent on this module, its not working. Below is the sample code.

````javascript
describe("Testing Firm Controller -->", function () {
   beforeEach(function () {
        module('ui.router');
        module('uirouteManagerModule');
        module('ngRoute');
        module('ngResource');
        module('ui.bootstrap');
        module('validation');
        module('angularCSS');
        module('ngSanitize');
        module('ngFileUpload');
        module("firm");
        module("globalModule");
        module("contentModule");
        
        //angular.mock.module("firm");
       
    });

    beforeEach(inject(function ($controller, $rootScope) {
    //beforeEach(inject(function ($controller, $rootScope, corp, profileSharedService) {
        //  beforeEach(inject(function ($controller, $rootScope, corp) {
        mockScope = $rootScope.$new();

        mockfirmController = $controller('firmController',
           {
               $scope: mockScope
           });
        /*mockCorpService = corp;
        mockprofileSharedService = profileSharedService;*/
      //  mockfirmServiceExtended = firmServiceExtended;
       // mockprofileServiceExtended = profileServiceExtended;


    }));


    /* it('Load Firm Info Controller',
         function () {
             expect(mockfirmInfoController).not.toBeNull();
         });*/
    it('Testing Firm Controller to be defined',
        function () {
            expect(mockfirmController).toBeDefined();
        });
});
````

Here, module("firm"); is dynamically generated module from the code. And, it should load 'firmController' but its not even going into before each function. 

However, I have similar case, where in I have concrete module file present, there its working fine.

Hence, just wanted to understand for mocking module, do we need to have physical file present?
Can we mock any module which is getting created dynamically?

Thanks,
Rahul

**Comment by slackersoft** [comment]
You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Additionally, it sounds like you are having issues/questions with Angular and/or ngMock, so you would probably be better served asking your questions with those teams.

Closing. Thanks for using Jasmine!

**Comment by rahulsahay19** [comment]
Thanks!
