### ISSUE TITLE
Add `done()` documentation

### ISSUE THREAD

**Issue by NoelBroda** [jasmine/jasmine.github.io#67]
Hi guys.
I can not find any documentation related about the parameters that `done()` receive.

I don't know why (because lack of documentation) but when I call `done()` function with a parameter, like: `done(true)`, the test fail.

Can you add documentation about it?
Thanks

**Comment by slackersoft** [comment]
The docs for `done` are in the [async section](https://jasmine.github.io/edge/introduction#section-Asynchronous_Support)

Jasmine also shouldn't be failing a spec when a parameter is passed to `done`, you can see the discussion in jasmine/jasmine#567 with the discussion on why that isn't the case.

**Comment by NoelBroda** [comment]
@slackersoft... But, you are saying that `done(true)` should not fail, but if you do that, the test will fail!.
Can you give me a clue where can I add that unit test?

**Comment by slackersoft** [comment]
See my comments in jasmine/jasmine#1254, but Jasmine's built-in `done` definitely ignores any arguments that are passed to it.
