### ISSUE TITLE
More examples to get a taste of jasmine

### ISSUE THREAD

**Issue by techtonik** [jasmine/jasmine.github.io#70]
There are not enough content to understand how a jasmine based tests would look like. I am particularly interested in testing dynamic browser widgets that are loaded in iframe.

**Comment by slackersoft** [comment]
We're still in the process of updating the docs site to work better for everyone, and one of the things we're looking at is some better tutorial type things. That said, your example sounds very specific to your use-case and would also primarily be about talking across iframes and not necessarily anything about Jasmine itself.

Closing. Thanks for using Jasmine!

**Comment by techtonik** [comment]
Do I get it right that Jasmine is a not a fit my use case or I should look elsewhere for JavaScript testing framework?

**Comment by slackersoft** [comment]
Regardless of which javascript testing framework you use, I would recommend testing the code that you put inside the `iframe` rather then testing it by actually running it there. Jasmine should be pretty flexible for doing whatever kind of testing you want, but the example you're asking for isn't something that would be very generalizable, so I don't think it belongs in Jasmine's docs.

**Comment by techtonik** [comment]
So what is Jasmine role then? Just a tool to execute tools that do real testing?

**Comment by slackersoft** [comment]
Jasmine is a javascript testing framework in a BDD style. It gives you the ability to run javascript and set expectations. It will report the results of the expectations and tell you if any of them failed. Jasmine does _**not**_ know anything about your domain, or whether or not the specs are being run within a browser or node.js. If it did, Jasmine would end up tied to a single solution and wouldn't be able to work in others.

Hope this helps. Thanks for using Jasmine!
