### ISSUE TITLE
update https://jasmine.github.io/2.0/ajax.html with current code

### ISSUE THREAD

**Issue by HolgerJeromin** [jasmine/jasmine.github.io#78]
The [documentation page](https://jasmine.github.io/2.0/ajax.html) runs and describes an old version of this library.

`jasmine.Ajax.requests.mostRecent().response({` 
is now
`jasmine.Ajax.requests.mostRecent().respondWith({` 

related #54

**Comment by slackersoft** [comment]
The page you linked to is for the 2.0 version of Jasmine, in which the `response` syntax is correct. Later versions of Jasmine Ajax updated and starting with the [2.2](https://jasmine.github.io/2.2/ajax.html) version of the docs, the new `respondWith` syntax is documented.

Hope this helps. Thanks for using Jasmine!
