### ISSUE TITLE
TypeError: Cannot read property 'links' of undefined

### ISSUE THREAD

**Issue by sarav0689** [jasmine/jasmine.github.io#81]
Hi Team,

When I run my test code I receive an error (TypeError: Cannot read property 'links' of undefined). Can anyone please help me on this.

Regards,
saravanan

**Comment by slackersoft** [comment]
You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.
