### ISSUE TITLE
Missing documentation in .calls.all() , .calls.mostRecent() and .calls.first() about invocationOrder

### ISSUE THREAD

**Issue by abhishek-parmar1** [jasmine/jasmine.github.io#83]
.calls.all() , 
.calls.mostRecent()  ,
.calls.first() ,
All these methods returns an object representing about the the context (the this) and arguments of the call, but they also return an key invocationOrder which represents the index of the function call. It is missing in the documentation.
[https://jasmine.github.io/2.0/introduction.html](url)

**Comment by slackersoft** [comment]
We're still in the process of figuring out which type of docs go where. This seems like something that should be in API docs, which should be here: https://jasmine.github.io/api/edge/Spy_calls.html

Hope this helps. Thanks for using Jasmine!
