### ISSUE TITLE
enhancement or change?

### ISSUE THREAD

**Issue by KipOmaha** [jasmine/jasmine.github.io#85]
Hi guys sweet javascript library, I made a change to the `jasmine-html.js` file so that it sets the `id` attribute to be the same as the `className` of the `jasmine_html-reporter` container.  

I did this so that I could target the id of the container instead of the class name, it helps for creating custom themes. 

I'm currently using version 2.5.2. So far it works great with the change. I was wondering if this idea is rolling around for any future updates or if it could be?

**Comment by KipOmaha** [comment]
sorry if this is the wrong spot for this.

**Comment by slackersoft** [comment]
I don't think this is something we're looking to change in Jasmine right now. If you're using CSS selectors, it should be just as easy to pick out the `class` as it is the `id`. Additionally, please take a look at [Jasmine's contributing guide](https://github.com/jasmine/jasmine/blob/master/.github/CONTRIBUTING.md) if you want to propose an enhancement in the future.

This repo is for the docs that live at [jasmine.github.io](https://jasmine.github.io), the repository for Jasmine itself is at [github.com/jasmine/jasmine](https://github.com/jasmine/jasmine).

I'm going to close this. Thanks for using Jasmine!
