### ISSUE TITLE
Introduction.js 3.1 does not pass the test

### ISSUE THREAD

**Issue by andrew-vandenbrink** [jasmine/jasmine.github.io#90]
```
expect(whatAmI.and.identity()).toEqual('whatAmI');

whatAmI.and.identity() // error not a function

whatAmI.and.identity // return "whatAmI"
```
![image](https://user-images.githubusercontent.com/12871379/37024391-001dea00-2129-11e8-8572-1fadd76138ab.png)

Using the latest jasmine 3.1
Not sure if jasmine bug or not updated documentation

**Comment by slackersoft** [comment]
Oops. Thanks for the report. The old running docs aren't being updated for 3.x Jasmine. Our hope is that the tutorials and API docs solve the documentation problems a bit better than the large prose-based documentation. I'm going to remove the "edge" docs from the archive section.
